### PR TITLE
Sync

### PR DESCRIPTION
**Pull request by gabi-250**
This brings `master` up-to-date with the upstream `master`.

### CODE REVIEW

**Comment by vext01** [comment]
OK.

I notice that some new files we've introduced don't have a license. Is that intentional?

**Comment by gabi-250** [comment]
@vext01 This particular PR doesn't introduce any new files. 

You're right, the files that are already in `master` don't have a license, but they probably should. I will open a separate PR for that.

**Comment by vext01** [comment]
OK.

Shall we merge this as is then?

**Comment by vext01** [comment]
(do we bors this one?)

**Comment by gabi-250** [comment]
I tried this out myself, but I think we should bors it just in case.

**Comment by vext01** [comment]
Ready for merge then?

**Comment by gabi-250** [comment]
yep

**Pull request merged**
