### PR TITLE
Move IR-related files to `librustc_codegen_ironox/ir`.

### PR DESCRIPTION
**Pull request by gabi-250**
This doesn't contain any major changes.

* Rename `ironox_type.rs` to `type_.rs` for consistency (`librustc_codegen_ssa` and `librustc_codegen_llvm` call this file `type_.rs`)
* Move everything IR-related to `librustc_codegen_ironox/ir`
* Define the `Instruction` type
* Add several new variants to `Value` (these will be used later)

### CODE REVIEW

**Comment by vext01** [comment]
LGTM.

(Not the disabled merge button :) )

**Comment by gabi-250** [comment]
Do you want me to change anything before you `bors r+`?

**Comment by vext01** [comment]
I was waiting to see if the other reviewer would find anything.

@ltratt ?

**Comment by vext01** [comment]
Actually, I think he said he's in meetings today. It's a straight forward change, so let's push on.

bors r+

**Pull request merged**
